[package]
name = "decompress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
csv = "1.1"
parquet = "46.0.0"
parquet_derive = "46.0.0"

